<?php

namespace justinholtweb\scrub\targets;

use Craft;
use craft\base\ElementInterface;
use craft\db\Query;
use craft\elements\Category;
use craft\elements\Entry;
use craft\errors\OperationAbortedException;
use justinholtweb\scrub\models\Rule;
use justinholtweb\scrub\models\Scope;

/**
 * Slugs — and, through them, URIs.
 *
 * Renaming a product line means renaming its URLs, and this is the part every find-and-replace tool
 * leaves you to do by hand. Only the slug is offered as a slot: the URI is *derived* from it by the
 * section's URI format, so it is regenerated by the save rather than replaced independently. Editing
 * a URI directly produces an element whose slug and URI disagree, which nothing in Craft expects.
 *
 * Craft keeps URIs unique on save, so a replacement that collides ends up as `about-us-2` rather
 * than as a failed run — which is worth knowing before pressing the button, and is why the preview
 * shows the slug and not the URL.
 */
class SlugTarget extends ElementTarget
{
    public const SLOT_SLUG = 'slug';

    public static function handle(): string
    {
        return 'slugs';
    }

    public function label(): string
    {
        return Craft::t('scrub', 'Slugs and URLs');
    }

    public function description(): string
    {
        return Craft::t('scrub', 'Entry and category slugs. URIs are regenerated from the slug, so links follow.');
    }

    protected function elementTypes(): array
    {
        return [Entry::class, Category::class];
    }

    protected function slotsFor(ElementInterface $element, Scope $scope): array
    {
        if (!$scope->wantsSlot(self::SLOT_SLUG) || ($element->slug ?? '') === '') {
            return [[], []];
        }

        return [
            [self::SLOT_SLUG => (string)$element->slug],
            [self::SLOT_SLUG => Craft::t('app', 'Slug')],
        ];
    }

    protected function applyValues(ElementInterface $element, array $values): void
    {
        if (!isset($values[self::SLOT_SLUG])) {
            return;
        }

        $element->slug = (string)$values[self::SLOT_SLUG];

        if (!$element::hasUris() || $element->getUriFormat() === null) {
            return;
        }

        // Regenerated explicitly, rather than by clearing `uri` and hoping the save rebuilds it.
        //
        // In Craft, the URI is computed by a *validator* (`ElementUriValidator`), and every element
        // Scrub writes is saved with validation off — deliberately, because an entry that has been
        // in the database for four years may no longer satisfy a field that was made required last
        // month, and refusing to fix a typo in it helps nobody. The consequence is that a slug
        // changed here regenerates no URI at all: the page's URL is simply *emptied*, and the entry
        // stops being reachable.
        //
        // `setElementUri()` is the public API for exactly this (Craft 4.6+) and keeps URIs unique
        // the same way a normal save would.
        $element->uri = null;

        try {
            Craft::$app->getElements()->setElementUri($element);
        } catch (OperationAbortedException) {
            // No unique URI could be produced — a disabled element with no home to go to. Leaving
            // the URI empty is what Craft itself does here.
        }
    }

    protected function applyPrefilter(Query $query, Rule $rule): void
    {
        $needle = $this->needle($rule);

        if ($needle === null) {
            return;
        }

        $query->andWhere($this->like('elements_sites.slug', $needle));
    }
}
